version: 1
labels:
  - label: 'FIX'
    title: '(?i)(\bfix\b|\bbug\b|버그|수정)'
  - label: 'FIX'
    branch: '(?i)^fix/'

  - label: 'FEAT'
    title: '(?i)(\bfeat\b|\bfeature\b|기능)'
  - label: 'FEAT'
    branch: '(?i)^feat/'

  - label: 'DOCS'
    title: '(?i)(\bdocs?\b|문서)'
  - label: 'DOCS'
    branch: '(?i)^docs/'

  - label: 'CHORE'
    title: '(?i)(\bchore\b|\bci\b|\bconfig\b)'
  - label: 'CHORE'
    branch: '(?i)^chore/'

  - label: 'REFACTOR'
    title: '(?i)(\brefactor\b|리팩터|리팩토링)'
  - label: 'REFACTOR'
    branch: '(?i)^refactor/'

  - label: 'REMOVE'
    title: '(?i)(\bremove\b|\bdelete\b|삭제)'
  - label: 'REMOVE'
    branch: '(?i)^remove/'

  - label: 'RENAME'
    title: '(?i)(\brename\b|\bmove\b|이름|이동)'
  - label: 'RENAME'
    branch: '(?i)^rename/'

  - label: 'STYLE'
    title: '(?i)(\bstyle\b|\bformat\b|\bprettier\b|포맷)'
  - label: 'STYLE'
    branch: '(?i)^style/'

  - label: 'wontfix'
    title: '(?i)(\bwontfix\b|won''t fix|작업하지 않음)'

  - label: '민수'
    authors: ['Tnalxmsk']

  - label: '소이'
    authors: ['soyyyyy']

  - label: '다경'
    authors: ['hdg0116']

  - label: '채원'
    authors: ['chaewon41']

  - label: '현종'
    authors: ['Navi-Up']
