import { styleVariants } from '@vanilla-extract/css';
import type { StyleRule } from '@vanilla-extract/css';

const base = {
  fontFamily: '"Pretendard", sans-serif',
  fontStyle: 'normal',
} satisfies StyleRule;

export const typography = {
  'display-1-bold': {
    ...base,
    fontSize: '5.6rem',
    fontWeight: 700,
    lineHeight: 1.4,
    letterSpacing: '-0.01rem',
  },
  'display-2-medium': {
    ...base,
    fontSize: '4rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.01rem',
  },
  'title-1-semibold': {
    ...base,
    fontSize: '3.2rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.01rem',
  },
  'title-1-medium': {
    ...base,
    fontSize: '3.2rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.01rem',
  },
  'title-2-semibold': {
    ...base,
    fontSize: '2.8rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'title-2-medium': {
    ...base,
    fontSize: '2.8rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.01rem',
  },
  'heading-1-semibold': {
    ...base,
    fontSize: '2.4rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-1-medium': {
    ...base,
    fontSize: '2.4rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-1-regular': {
    ...base,
    fontSize: '2.4rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-2-semibold': {
    ...base,
    fontSize: '2.2rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-2-medium': {
    ...base,
    fontSize: '2.2rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-2-regular': {
    ...base,
    fontSize: '2.2rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-3-semibold': {
    ...base,
    fontSize: '2rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-3-medium': {
    ...base,
    fontSize: '2rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'heading-3-regular': {
    ...base,
    fontSize: '2rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-1-semibold': {
    ...base,
    fontSize: '1.8rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-1-medium': {
    ...base,
    fontSize: '1.8rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-1-regular': {
    ...base,
    fontSize: '1.8rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-2-semibold': {
    ...base,
    fontSize: '1.6rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-2-medium': {
    ...base,
    fontSize: '1.6rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-2-regular': {
    ...base,
    fontSize: '1.6rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-3-semibold': {
    ...base,
    fontSize: '1.4rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-3-medium': {
    ...base,
    fontSize: '1.4rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'body-3-regular': {
    ...base,
    fontSize: '1.4rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'caption-1-medium': {
    ...base,
    fontSize: '1.2rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'caption-1-regular': {
    ...base,
    fontSize: '1.2rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'caption-1-light': {
    ...base,
    fontSize: '1.2rem',
    fontWeight: 300,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'caption-2-medium': {
    ...base,
    fontSize: '1rem',
    fontWeight: 500,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'caption-2-regular': {
    ...base,
    fontSize: '1rem',
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
  'caption-2-light': {
    ...base,
    fontSize: '1rem',
    fontWeight: 300,
    lineHeight: 1.4,
    letterSpacing: '-0.02rem',
  },
} satisfies Record<string, StyleRule>;

export const text = styleVariants(typography);
