export const SIDEBAR_LAYOUT_SIDEBAR_WIDTH_PX = 290;
export const SIDEBAR_LAYOUT_SIDEBAR_WIDTH = `${SIDEBAR_LAYOUT_SIDEBAR_WIDTH_PX}px`;
export const SIDEBAR_LAYOUT_TOAST_CENTER_OFFSET_X = `${SIDEBAR_LAYOUT_SIDEBAR_WIDTH_PX / 2}px`;
export const SIDEBAR_LAYOUT_TOAST_OFFSET_Y = '2rem';
