import type { NearbyMarketDtoTypes } from '../model/nearby-markets-schema';

type MarketTemplateTypes = Omit<NearbyMarketDtoTypes, 'marketId' | 'slug'>;

const MARKET_TEMPLATES: readonly MarketTemplateTypes[] = [
  {
    address: '서울특별시 마포구 망원동 123-45',
    distance: '350m',
    isOpen: true,
    latitude: 37.5563,
    longitude: 126.9013,
    name: '망원 신선마트',
    previewProducts: [
      {
        discountRate: 10,
        discountedPrice: 6900,
        name: '삼겹살 500g',
        originalPrice: 7700,
        productId: 101,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 6900,
        name: '재래식 된장 1kg',
        originalPrice: 6900,
        productId: 102,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 6900,
        name: '태양초 고추장 1kg',
        originalPrice: 6900,
        productId: 103,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 24,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 마포구 망원동 78-12',
    distance: '480m',
    isOpen: true,
    latitude: 37.5559,
    longitude: 126.9027,
    name: '망원시장 청과',
    previewProducts: [
      {
        discountRate: 15,
        discountedPrice: 12900,
        name: '부사 사과 3kg',
        originalPrice: 15200,
        productId: 201,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 3900,
        name: '바나나 1송이',
        originalPrice: 3900,
        productId: 202,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 5900,
        name: '완숙 토마토 1kg',
        originalPrice: 5900,
        productId: 203,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 18,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 마포구 연남동 210-3',
    distance: '620m',
    isOpen: true,
    latitude: 37.5636,
    longitude: 126.9252,
    name: '연남 정육점',
    previewProducts: [
      {
        discountRate: 20,
        discountedPrice: 24900,
        name: '한우 등심 300g',
        originalPrice: 31100,
        productId: 301,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 8900,
        name: '국내산 계란 30구',
        originalPrice: 8900,
        productId: 302,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 9900,
        name: '냉장 닭가슴살 1kg',
        originalPrice: 9900,
        productId: 303,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 15,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 서대문구 연희동 88-1',
    distance: '810m',
    isOpen: false,
    latitude: 37.5657,
    longitude: 126.9346,
    name: '연희 로컬푸드',
    previewProducts: [
      {
        discountRate: 0,
        discountedPrice: 2900,
        name: '유기농 상추 200g',
        originalPrice: 2900,
        productId: 401,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 10,
        discountedPrice: 9900,
        name: '제철 딸기 500g',
        originalPrice: 11000,
        productId: 402,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 1900,
        name: '두부 1모',
        originalPrice: 1900,
        productId: 403,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 9,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 강남구 역삼동 45-6',
    distance: '950m',
    isOpen: true,
    latitude: 37.5,
    longitude: 127.0364,
    name: '역삼 프리미엄마트',
    previewProducts: [
      {
        discountRate: 12,
        discountedPrice: 15900,
        name: '로스트비프 300g',
        originalPrice: 18100,
        productId: 501,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 4500,
        name: '유기농 우유 1L',
        originalPrice: 4500,
        productId: 502,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 8900,
        name: '수제 파스타 소스',
        originalPrice: 8900,
        productId: 503,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 31,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 종로구 익선동 12-3',
    distance: '1.2km',
    isOpen: false,
    latitude: 37.573,
    longitude: 126.991,
    name: '익선동 전통시장',
    previewProducts: [
      {
        discountRate: 0,
        discountedPrice: 5900,
        name: '모듬떡 세트',
        originalPrice: 5900,
        productId: 601,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 10,
        discountedPrice: 3900,
        name: '녹두빈대떡',
        originalPrice: 4300,
        productId: 602,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 4900,
        name: '삼색나물 반찬',
        originalPrice: 4900,
        productId: 603,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 12,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 성동구 성수동2가 300-1',
    distance: '1.5km',
    isOpen: true,
    latitude: 37.5446,
    longitude: 127.0559,
    name: '성수동 그로서리',
    previewProducts: [
      {
        discountRate: 15,
        discountedPrice: 6900,
        name: '수제 소시지 4입',
        originalPrice: 8100,
        productId: 701,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 7900,
        name: '크래프트 맥주 안주세트',
        originalPrice: 7900,
        productId: 702,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 5900,
        name: '유기농 샐러드 채소',
        originalPrice: 5900,
        productId: 703,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 20,
    thumbnailUrl: '/exampleImg.png',
  },
  {
    address: '서울특별시 용산구 이태원동 34-7',
    distance: '2.1km',
    isOpen: true,
    latitude: 37.5344,
    longitude: 126.9946,
    name: '이태원 글로벌마트',
    previewProducts: [
      {
        discountRate: 0,
        discountedPrice: 12900,
        name: '수입 치즈 플래터',
        originalPrice: 12900,
        productId: 801,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 10,
        discountedPrice: 6900,
        name: '멕시칸 살사소스',
        originalPrice: 7700,
        productId: 802,
        thumbnailUrl: '/exampleImg.png',
      },
      {
        discountRate: 0,
        discountedPrice: 9900,
        name: '할랄 인증 소고기 500g',
        originalPrice: 9900,
        productId: 803,
        thumbnailUrl: '/exampleImg.png',
      },
    ],
    productCount: 17,
    thumbnailUrl: '/exampleImg.png',
  },
];

const MOCK_TOTAL_COUNT = 24;

const buildMockNearbyMarkets = (): NearbyMarketDtoTypes[] => {
  return Array.from({ length: MOCK_TOTAL_COUNT }, (_, index) => {
    const template = MARKET_TEMPLATES[index % MARKET_TEMPLATES.length]!;
    const cycle = Math.floor(index / MARKET_TEMPLATES.length) + 1;

    return {
      ...template,
      marketId: index + 1,
      name: cycle === 1 ? template.name : `${template.name} ${cycle}호점`,
      slug: `market-${index + 1}`,
    };
  });
};

export const MOCK_NEARBY_MARKETS: readonly NearbyMarketDtoTypes[] = buildMockNearbyMarkets();
