export const PRESIGNED_UPLOAD_PURPOSE = {
  DEFAULT_PRODUCT_THUMBNAIL: 'DEFAULT_PRODUCT_THUMBNAIL',
  MARKET_THUMBNAIL: 'MARKET_THUMBNAIL',
  PRODUCT_IMPORT_EXCEL: 'PRODUCT_IMPORT_EXCEL',
  PRODUCT_THUMBNAIL: 'PRODUCT_THUMBNAIL',
} as const;

export type PresignedUploadPurposeTypes =
  (typeof PRESIGNED_UPLOAD_PURPOSE)[keyof typeof PRESIGNED_UPLOAD_PURPOSE];

export const PRESIGNED_UPLOAD_PURPOSE_LABEL = {
  [PRESIGNED_UPLOAD_PURPOSE.DEFAULT_PRODUCT_THUMBNAIL]: '기본 이미지(관리자)',
  [PRESIGNED_UPLOAD_PURPOSE.MARKET_THUMBNAIL]: '마트 이미지(점주)',
  [PRESIGNED_UPLOAD_PURPOSE.PRODUCT_IMPORT_EXCEL]: '일괄등록 엑셀(점주)',
  [PRESIGNED_UPLOAD_PURPOSE.PRODUCT_THUMBNAIL]: '상품 이미지(점주)',
} as const satisfies Record<PresignedUploadPurposeTypes, string>;
