name: Pull Request Labeler

permissions:
  contents: read
  issues: write

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: srvaroa/labeler@v1.13.0
        with:
          config_path: .github/labeler.yml
          use_local_config: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
